### ISSUE TITLE
Make file paths configurable

### ISSUE THREAD

**Issue by shawnrc** [The-f6X/Gen4OverlayScript#4]
hardcoded paths are ass and make it hard to test across machines

#### Tasks:
- [x] extract write targets

**Comment by shawnrc** [comment]
@The-f6X can you describe what the output directory layout relative to where `Script.py` lives should look like?

**Comment by The-f6X** [comment]
I was thinking of just having it be structured like this:
```
\NDSRead\
   Script.py
   Gen4.Lua
   Gen5.Lua
   Team.txt
   \Pokemon_Images\
   \Outputs\
       Member1.png
       Health1.png
       Member1.txt
        ...
```

**Comment by shawnrc** [comment]
Okay, I've set the defaults to match this layout, with a few name changes for convention and consistency's sake:

```
Team.txt -> team.txt
Pokemon_Images -> assets
Outputs -> out
```
